<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>HSE Events Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        h1 { font-size: 18px; color: #1e5f9e; }
        h2 { font-size: 14px; color: #333; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; }
        th { background-color: #1e5f9e; color: white; }
        .severity-critical { color: #dc2626; font-weight: bold; }
        .severity-high { color: #ea580c; font-weight: bold; }
        .severity-medium { color: #ca8a04; }
        .severity-low { color: #16a34a; }
        .status-open { color: #dc2626; }
        .status-closed { color: #16a34a; }
        .meta { margin-bottom: 20px; }
        .meta-item { margin: 5px 0; }
        .footer { margin-top: 30px; font-size: 10px; color: #666; text-align: center; }
    </style>
</head>
<body>
    <h1>HSE Events Report</h1>
    
    <div class="meta">
        @if($project)
            <div class="meta-item"><strong>Project:</strong> {{ $project->name }}</div>
        @endif
        @if($dateFrom && $dateTo)
            <div class="meta-item"><strong>Period:</strong> {{ $dateFrom }} to {{ $dateTo }}</div>
        @endif
        <div class="meta-item"><strong>Total Events:</strong> {{ count($events) }}</div>
        <div class="meta-item"><strong>Generated:</strong> {{ $generatedAt->format('Y-m-d H:i:s') }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Reference</th>
                <th>Type</th>
                <th>Severity</th>
                <th>Status</th>
                <th>Title</th>
                <th>Location</th>
                <th>Occurred At</th>
                <th>Reporter</th>
            </tr>
        </thead>
        <tbody>
            @forelse($events as $event)
                <tr>
                    <td>{{ $event->reference }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $event->type)) }}</td>
                    <td class="severity-{{ $event->severity }}">{{ ucfirst($event->severity) }}</td>
                    <td class="status-{{ $event->status }}">{{ ucfirst(str_replace('_', ' ', $event->status)) }}</td>
                    <td>{{ $event->title }}</td>
                    <td>{{ $event->location ?? 'N/A' }}</td>
                    <td>{{ $event->occurred_at?->format('Y-m-d H:i') }}</td>
                    <td>{{ $event->reporter?->name ?? 'N/A' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align: center;">No events found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by HSE SaaS Platform
    </div>
</body>
</html>
